# MySQL.  Versions 4.1 and 5.0 are recommended.
#
#
# Be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: postgresql
  host: 127.0.0.1
  username: loomio_db_user
  password: loomio_db_user_pass
  database: loomio_db_development

test:
  adapter: postgresql
  host: localhost
  username: loomio_db_user
  password: loomio_db_user_pass
  database: loomio_db_test

production:
  adapter: postgresql
  host: 127.0.0.1
  username: loomio_db_user
  password: loomio_db_user_pass
  database: loomio_db_development

