common: &common
  server: "<%= ENV.fetch('FAYE_URL', 'http://localhost:9292/faye') %>"
  secret_token: "<%= ENV.fetch('PRIVATE_PUB_SECRET_TOKEN', 'secret') %>"

development:
  <<: *common
test:
  <<: *common

production:
  <<: *common
  signature_expiration: 7200
