default: &default
  secret_key_base: <%= ENV['SECRET_COOKIE_TOKEN'] %>
  airbrake_api_key:  <%= ENV['AIRBRAKE_API_KEY'] %>
  devise: <%= ENV['DEVISE_SECRET'] %>
  google_key: <%= ENV['GOOGLE_KEY'] %>
  google_secret: <%= ENV['GOOGLE_SECRET'] %>
  twitter_key: <%= ENV['TWITTER_KEY'] %>
  twitter_secret: <%= ENV['TWITTER_SECRET'] %>
  facebook_key: <%= ENV['FACEBOOK_KEY'] %>
  facebook_secret: <%= ENV['FACEBOOK_SECRET'] %>
  intercom_app_id: <%= ENV['INTERCOM_APP_ID'] %>
  intercom_app_secret: <%= ENV['INTERCOM_APP_SECRET'] %>
  intercom_app_api_key: <%= ENV['INTERCOM_APP_API_KEY'] %>
  omni_contacts_google_key: <%= ENV['OMNI_CONTACTS_GOOGLE_KEY'] %>
  omni_contacts_google_secret: <%= ENV['OMNI_CONTACTS_GOOGLE_SECRET'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  chargify_app_name: <%= ENV['CHARGIFY_APP_NAME'] %>
  chargify_api_key: <%= ENV['CHARGIFY_API_KEY'] %>
  chargify_donation_url: <%= ENV['CHARGIFY_DONATION_URL'] %>
  chargify_plus_plan_key: <%= ENV['CHARGIFY_PLUS_PLAN_KEY'] %>
  chargify_plus_plan_name: <%= ENV['CHARGIFY_PLUS_PLAN_NAME'] %>
  chargify_standard_plan_key: <%= ENV['CHARGIFY_STANDARD_PLAN_KEY'] %>
  chargify_standard_plan_name: <%= ENV['CHARGIFY_STANDARD_PLAN_NAME'] %>

development:
  <<: *default
  secret_key_base: asjdahkjda
  devise: abc123
  aws_access_key_id: AKIAJ36WZW2D64OIDJXQ
  aws_secret_access_key: 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
  aws_bucket: genteloomio
  aws_region: us-west-1
  facebook_key: 156220511387287
  facebook_secret: 9fd2193a2af03b67e2a19f409f99379a
  twitter_key: 9kI5Z1wdqF5X1mQQFVdja9Pun
  twitter_secret: FToJWcsb3fJeFC8iMv1cqO9tNXrvGtCwNfWRTxfPUgRkZUVQFt

test:
  <<: *default
  secret_key_base: asjdahkjda
  devise: abc123
  chargify_app_name: loomio-test
  chargify_api_key: fakeapikey
  aws_access_key_id: fakeaccesskeyid
  aws_secret_access_key: fakesecretaccesskey
  aws_bucket: fakebucketname

staging:
  <<: *default

production:
  <<: *default
  secret_key_base: asjdahkjda
  devise: abc123
  aws_access_key_id: AKIAJ36WZW2D64OIDJXQ
  aws_secret_access_key: 9CA1Kct2I829snxaa8R2uQU1jtmsmNr3OBrE07zw
  aws_bucket: genteloomio
  aws_region: us-west-1
  facebook_key: 156220511387287
  facebook_secret: 9fd2193a2af03b67e2a19f409f99379a
  twitter_key: 9kI5Z1wdqF5X1mQQFVdja9Pun
  twitter_secret: FToJWcsb3fJeFC8iMv1cqO9tNXrvGtCwNfWRTxfPUgRkZUVQFt
